apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileprocessor
  namespace: eduhelper
spec:
  replicas: 6
  selector:
    matchLabels:
      app: fileprocessor
  template:
    metadata:
      labels:
        app: fileprocessor
    spec:
      containers:
      - name: fileprocessor
        image: 397789365835.dkr.ecr.ap-southeast-1.amazonaws.com/esd-eduhelper-eks-ecr-production:fileprocessor-70375fdab63f876ea51ed846873bfc7df4e3fa60
        imagePullPolicy: Always
        ports:
        - containerPort: 50053
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50053"]
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50053"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
status: {}